spring:
  mail:
    host: smtp.qq.com
    username: 568541648@qq.com
    password: nykrgvozkppmbbfa
  datasource:
    url: jdbc:mysql://localhost:3306/book_manage
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      username: root
      password: root
  redis:
    host: localhost
#    database: 0
#    port: 6379
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: true
  mvc:
#    swagger使用
    pathmatch:
      matching-strategy: ant_path_matcher




